public class Exceptions {
    public static String* makeExceptions() {
        try {
            switch (1) {
                case 1:
                case 0:
                    try {
                        throw new RuntimeException(":V #1");
                    } catch (RuntimeException e) {
                        yield "try within a try: " + e.toString();
                    }
            }
        } catch (RuntimeException e) {
            yield "THIS IS A BUG";
        }
        a();

        try {
            throw new RuntimeException(":V #2");
        } catch (RuntimeException e) {
            yield "catch behind a catch: " + e.toString();
        }
        throw new RuntimeException("\n\nTHIS EXCEPTION IS NOT AN ERROR! READ THE SOURCE FOR INFO!\n");
    }

    public static void main(String[] args) throws Exception {
        for (String estr : makeExceptions()) {
            System.out.println("Caught exception? " + estr);
        }
    }
}
